export const ENVIRONMENT = {
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL!,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  NEXT_SUPABASE_SERVICE_ROLE: process.env.NEXT_SUPABASE_SERVICE_ROLE!,
  NEXT_SUPABASE_DB_PASSWORD: process.env.NEXT_SUPABASE_DB_PASSWORD!,
  NODE_ENV: process.env.NODE_ENV,
};
